/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 13
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_COLON = 4,
  anon_sym_EQ = 5,
  anon_sym_LBRACK_RBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_t = 8,
  anon_sym_i = 9,
  anon_sym_b = 10,
  anon_sym_c = 11,
  anon_sym_r = 12,
  anon_sym_m = 13,
  anon_sym_p2 = 14,
  anon_sym_p3 = 15,
  anon_sym_p4 = 16,
  anon_sym_ip2 = 17,
  anon_sym_ip3 = 18,
  anon_sym_ip4 = 19,
  anon_sym_i64 = 20,
  sym__include_keyword = 21,
  sym_comment = 22,
  sym_string = 23,
  sym__parameter_value = 24,
  sym__simple_value = 25,
  sym__include_path = 26,
  sym__array_value = 27,
  sym__array_open = 28,
  sym__unexpected_line_break = 29,
  sym__quoted_type = 30,
  sym__quoted_include_keyword = 31,
  sym__text_after_nul = 32,
  sym__separator = 33,
  sym__error_sentinel = 34,
  sym_document = 35,
  sym__statement = 36,
  sym_block = 37,
  sym_parameter = 38,
  sym_array = 39,
  sym_include = 40,
  sym__name = 41,
  sym__type = 42,
  sym__value_separator = 43,
  sym_type = 44,
  sym__quoted_type_name = 45,
  aux_sym_document_repeat1 = 46,
  aux_sym_array_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACK_RBRACK] = "[]",
  [anon_sym_RBRACK] = "]",
  [anon_sym_t] = "t",
  [anon_sym_i] = "i",
  [anon_sym_b] = "b",
  [anon_sym_c] = "c",
  [anon_sym_r] = "r",
  [anon_sym_m] = "m",
  [anon_sym_p2] = "p2",
  [anon_sym_p3] = "p3",
  [anon_sym_p4] = "p4",
  [anon_sym_ip2] = "ip2",
  [anon_sym_ip3] = "ip3",
  [anon_sym_ip4] = "ip4",
  [anon_sym_i64] = "i64",
  [sym__include_keyword] = "include",
  [sym_comment] = "comment",
  [sym_string] = "string",
  [sym__parameter_value] = "raw_value",
  [sym__simple_value] = "raw_value",
  [sym__include_path] = "raw_value",
  [sym__array_value] = "raw_value",
  [sym__array_open] = "[",
  [sym__unexpected_line_break] = "_unexpected_line_break",
  [sym__quoted_type] = "string",
  [sym__quoted_include_keyword] = "include",
  [sym__text_after_nul] = "_text_after_nul",
  [sym__separator] = ";",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_document] = "document",
  [sym__statement] = "_statement",
  [sym_block] = "block",
  [sym_parameter] = "parameter",
  [sym_array] = "array",
  [sym_include] = "include",
  [sym__name] = "_name",
  [sym__type] = "_type",
  [sym__value_separator] = "_value_separator",
  [sym_type] = "type",
  [sym__quoted_type_name] = "type",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACK_RBRACK] = anon_sym_LBRACK_RBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_t] = anon_sym_t,
  [anon_sym_i] = anon_sym_i,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_c] = anon_sym_c,
  [anon_sym_r] = anon_sym_r,
  [anon_sym_m] = anon_sym_m,
  [anon_sym_p2] = anon_sym_p2,
  [anon_sym_p3] = anon_sym_p3,
  [anon_sym_p4] = anon_sym_p4,
  [anon_sym_ip2] = anon_sym_ip2,
  [anon_sym_ip3] = anon_sym_ip3,
  [anon_sym_ip4] = anon_sym_ip4,
  [anon_sym_i64] = anon_sym_i64,
  [sym__include_keyword] = sym__quoted_include_keyword,
  [sym_comment] = sym_comment,
  [sym_string] = sym_string,
  [sym__parameter_value] = sym__parameter_value,
  [sym__simple_value] = sym__parameter_value,
  [sym__include_path] = sym__parameter_value,
  [sym__array_value] = sym__parameter_value,
  [sym__array_open] = sym__array_open,
  [sym__unexpected_line_break] = sym__unexpected_line_break,
  [sym__quoted_type] = sym_string,
  [sym__quoted_include_keyword] = sym__quoted_include_keyword,
  [sym__text_after_nul] = sym__text_after_nul,
  [sym__separator] = sym__separator,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_document] = sym_document,
  [sym__statement] = sym__statement,
  [sym_block] = sym_block,
  [sym_parameter] = sym_parameter,
  [sym_array] = sym_array,
  [sym_include] = sym_include,
  [sym__name] = sym__name,
  [sym__type] = sym__type,
  [sym__value_separator] = sym__value_separator,
  [sym_type] = sym_type,
  [sym__quoted_type_name] = sym_type,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_c] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_r] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_m] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_p4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ip2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ip3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ip4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [sym__include_keyword] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__parameter_value] = {
    .visible = true,
    .named = true,
  },
  [sym__simple_value] = {
    .visible = true,
    .named = true,
  },
  [sym__include_path] = {
    .visible = true,
    .named = true,
  },
  [sym__array_value] = {
    .visible = true,
    .named = true,
  },
  [sym__array_open] = {
    .visible = true,
    .named = false,
  },
  [sym__unexpected_line_break] = {
    .visible = false,
    .named = true,
  },
  [sym__quoted_type] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_include_keyword] = {
    .visible = true,
    .named = false,
  },
  [sym__text_after_nul] = {
    .visible = false,
    .named = true,
  },
  [sym__separator] = {
    .visible = true,
    .named = false,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym__name] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym__value_separator] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_type_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_path = 2,
  field_type = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_path] = "path",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 1},
  [4] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 1},
  [6] = {.index = 4, .length = 1},
  [7] = {.index = 5, .length = 2},
  [8] = {.index = 7, .length = 3},
  [9] = {.index = 10, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_path, 1},
  [2] =
    {field_path, 2},
  [3] =
    {field_name, 0, .inherited = true},
  [4] =
    {field_type, 0},
  [5] =
    {field_name, 0, .inherited = true},
    {field_value, 2},
  [7] =
    {field_name, 0, .inherited = true},
    {field_type, 2, .inherited = true},
    {field_value, 4},
  [10] =
    {field_name, 0, .inherited = true},
    {field_type, 2, .inherited = true},
    {field_value, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = sym_identifier,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '[') ADVANCE(1);
      if (lookahead == ']') ADVANCE(8);
      if (lookahead == '{') ADVANCE(3);
      if (lookahead == '}') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x1a ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(9);
      END_STATE();
    case 1:
      if (lookahead == ']') ADVANCE(7);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACK_RBRACK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(9);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'I', 1,
        'b', 2,
        'c', 3,
        'i', 4,
        'm', 5,
        'p', 6,
        'r', 7,
        't', 8,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == 0x1a ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_b);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_c);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_i);
      if (lookahead == '6') ADVANCE(10);
      if (lookahead == 'p') ADVANCE(11);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_m);
      END_STATE();
    case 6:
      if (lookahead == '2') ADVANCE(12);
      if (lookahead == '3') ADVANCE(13);
      if (lookahead == '4') ADVANCE(14);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_r);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_t);
      END_STATE();
    case 9:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == '4') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == '2') ADVANCE(17);
      if (lookahead == '3') ADVANCE(18);
      if (lookahead == '4') ADVANCE(19);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_p2);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_p3);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_p4);
      END_STATE();
    case 15:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_ip2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_ip3);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_ip4);
      END_STATE();
    case 20:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__include_keyword);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 4},
  [10] = {.lex_state = 0, .external_lex_state = 4},
  [11] = {.lex_state = 0, .external_lex_state = 4},
  [12] = {.lex_state = 0, .external_lex_state = 4},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 6},
  [26] = {.lex_state = 0, .external_lex_state = 7},
  [27] = {.lex_state = 0, .external_lex_state = 6},
  [28] = {.lex_state = 0, .external_lex_state = 8},
  [29] = {.lex_state = 0, .external_lex_state = 9},
  [30] = {.lex_state = 0, .external_lex_state = 9},
  [31] = {.lex_state = 0, .external_lex_state = 9},
  [32] = {.lex_state = 0, .external_lex_state = 10},
  [33] = {.lex_state = 0, .external_lex_state = 10},
  [34] = {.lex_state = 0, .external_lex_state = 6},
  [35] = {.lex_state = 0, .external_lex_state = 9},
  [36] = {.lex_state = 0, .external_lex_state = 10},
  [37] = {.lex_state = 0, .external_lex_state = 10},
  [38] = {.lex_state = 0, .external_lex_state = 10},
  [39] = {.lex_state = 0, .external_lex_state = 10},
  [40] = {.lex_state = 0, .external_lex_state = 11},
  [41] = {.lex_state = 0, .external_lex_state = 12},
  [42] = {.lex_state = 0, .external_lex_state = 10},
  [43] = {.lex_state = 0, .external_lex_state = 13},
  [44] = {.lex_state = 0, .external_lex_state = 5},
  [45] = {.lex_state = 0, .external_lex_state = 10},
  [46] = {.lex_state = 0, .external_lex_state = 10},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [anon_sym_i] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_c] = ACTIONS(1),
    [anon_sym_r] = ACTIONS(1),
    [anon_sym_m] = ACTIONS(1),
    [anon_sym_p2] = ACTIONS(1),
    [anon_sym_p3] = ACTIONS(1),
    [anon_sym_p4] = ACTIONS(1),
    [anon_sym_ip2] = ACTIONS(1),
    [anon_sym_ip3] = ACTIONS(1),
    [anon_sym_ip4] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [sym__include_keyword] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(1),
    [sym__parameter_value] = ACTIONS(1),
    [sym__simple_value] = ACTIONS(1),
    [sym__include_path] = ACTIONS(1),
    [sym__array_value] = ACTIONS(1),
    [sym__array_open] = ACTIONS(1),
    [sym__unexpected_line_break] = ACTIONS(1),
    [sym__quoted_type] = ACTIONS(1),
    [sym__quoted_include_keyword] = ACTIONS(1),
    [sym__text_after_nul] = ACTIONS(3),
    [sym__separator] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(46),
    [sym__statement] = STATE(4),
    [sym_block] = STATE(4),
    [sym_parameter] = STATE(4),
    [sym_include] = STATE(4),
    [sym__name] = STATE(33),
    [aux_sym_document_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym__include_keyword] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym_string] = ACTIONS(11),
    [sym__quoted_include_keyword] = ACTIONS(13),
    [sym__text_after_nul] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(17), 1,
      anon_sym_i,
    ACTIONS(19), 1,
      sym__quoted_type,
    STATE(27), 1,
      sym__quoted_type_name,
    STATE(39), 1,
      sym__type,
    STATE(42), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(15), 12,
      anon_sym_t,
      anon_sym_b,
      anon_sym_c,
      anon_sym_r,
      anon_sym_m,
      anon_sym_p2,
      anon_sym_p3,
      anon_sym_p4,
      anon_sym_ip2,
      anon_sym_ip3,
      anon_sym_ip4,
      anon_sym_i64,
  [34] = 8,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(26), 1,
      sym__include_keyword,
    ACTIONS(29), 1,
      sym_string,
    ACTIONS(32), 1,
      sym__quoted_include_keyword,
    STATE(33), 1,
      sym__name,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(3), 5,
      sym__statement,
      sym_block,
      sym_parameter,
      sym_include,
      aux_sym_document_repeat1,
  [65] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym__include_keyword,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym__quoted_include_keyword,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym__name,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    STATE(3), 5,
      sym__statement,
      sym_block,
      sym_parameter,
      sym_include,
      aux_sym_document_repeat1,
  [95] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym__include_keyword,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym__quoted_include_keyword,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym__name,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    STATE(6), 5,
      sym__statement,
      sym_block,
      sym_parameter,
      sym_include,
      aux_sym_document_repeat1,
  [125] = 8,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      sym__include_keyword,
    ACTIONS(11), 1,
      sym_string,
    ACTIONS(13), 1,
      sym__quoted_include_keyword,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym__name,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    STATE(3), 5,
      sym__statement,
      sym_block,
      sym_parameter,
      sym_include,
      aux_sym_document_repeat1,
  [155] = 5,
    ACTIONS(45), 1,
      sym__separator,
    STATE(21), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(43), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(41), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [176] = 5,
    ACTIONS(51), 1,
      sym__separator,
    STATE(19), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(49), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(47), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [197] = 5,
    ACTIONS(57), 1,
      sym__separator,
    STATE(15), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(55), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(53), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [218] = 5,
    ACTIONS(63), 1,
      sym__separator,
    STATE(17), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(61), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(59), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [239] = 5,
    ACTIONS(65), 1,
      sym__separator,
    STATE(18), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(49), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(47), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [260] = 5,
    ACTIONS(67), 1,
      sym__separator,
    STATE(20), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(43), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(41), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [281] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(71), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(69), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [296] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(75), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(73), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [311] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(79), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(77), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [326] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(83), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(81), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [341] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(87), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(85), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [356] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(91), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(89), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [371] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(91), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(89), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [386] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(95), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(93), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [401] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(95), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(93), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [416] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(99), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(97), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [431] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(103), 2,
      sym__include_keyword,
      sym_identifier,
    ACTIONS(101), 4,
      sym_string,
      sym__quoted_include_keyword,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [446] = 3,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(107), 2,
      sym_string,
      sym__include_path,
    ACTIONS(105), 3,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
  [460] = 4,
    ACTIONS(111), 1,
      sym__separator,
    STATE(32), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(109), 3,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
  [476] = 4,
    ACTIONS(115), 1,
      sym__separator,
    STATE(35), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(113), 3,
      sym_string,
      sym__array_value,
      anon_sym_RBRACK,
  [492] = 4,
    ACTIONS(119), 1,
      sym__separator,
    STATE(37), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(117), 2,
      anon_sym_EQ,
      anon_sym_LBRACK_RBRACK,
  [507] = 4,
    ACTIONS(121), 1,
      sym__separator,
    STATE(44), 1,
      sym__value_separator,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(107), 2,
      sym_string,
      sym__include_path,
  [522] = 4,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(125), 2,
      sym_string,
      sym__array_value,
  [537] = 4,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    STATE(29), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(125), 2,
      sym_string,
      sym__array_value,
  [552] = 4,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      aux_sym_array_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(131), 2,
      sym_string,
      sym__array_value,
  [567] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(134), 3,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
  [577] = 4,
    ACTIONS(136), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      anon_sym_COLON,
    ACTIONS(140), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
  [591] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(142), 3,
      sym__separator,
      anon_sym_EQ,
      anon_sym_LBRACK_RBRACK,
  [601] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(129), 3,
      sym_string,
      sym__array_value,
      anon_sym_RBRACK,
  [611] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(109), 3,
      anon_sym_LBRACE,
      anon_sym_COLON,
      anon_sym_EQ,
  [621] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(144), 2,
      anon_sym_EQ,
      anon_sym_LBRACK_RBRACK,
  [630] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(146), 2,
      anon_sym_EQ,
      anon_sym_LBRACK_RBRACK,
  [639] = 3,
    ACTIONS(148), 1,
      anon_sym_EQ,
    ACTIONS(150), 1,
      anon_sym_LBRACK_RBRACK,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
  [650] = 3,
    ACTIONS(152), 1,
      sym__array_open,
    STATE(22), 1,
      sym_array,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
  [661] = 3,
    ACTIONS(154), 1,
      sym_string,
    ACTIONS(156), 1,
      sym__parameter_value,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
  [672] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(117), 2,
      anon_sym_EQ,
      anon_sym_LBRACK_RBRACK,
  [681] = 3,
    ACTIONS(158), 1,
      sym_string,
    ACTIONS(160), 1,
      sym__simple_value,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
  [692] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
    ACTIONS(162), 2,
      sym_string,
      sym__include_path,
  [701] = 2,
    ACTIONS(164), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
  [709] = 2,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym__text_after_nul,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 65,
  [SMALL_STATE(5)] = 95,
  [SMALL_STATE(6)] = 125,
  [SMALL_STATE(7)] = 155,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 197,
  [SMALL_STATE(10)] = 218,
  [SMALL_STATE(11)] = 239,
  [SMALL_STATE(12)] = 260,
  [SMALL_STATE(13)] = 281,
  [SMALL_STATE(14)] = 296,
  [SMALL_STATE(15)] = 311,
  [SMALL_STATE(16)] = 326,
  [SMALL_STATE(17)] = 341,
  [SMALL_STATE(18)] = 356,
  [SMALL_STATE(19)] = 371,
  [SMALL_STATE(20)] = 386,
  [SMALL_STATE(21)] = 401,
  [SMALL_STATE(22)] = 416,
  [SMALL_STATE(23)] = 431,
  [SMALL_STATE(24)] = 446,
  [SMALL_STATE(25)] = 460,
  [SMALL_STATE(26)] = 476,
  [SMALL_STATE(27)] = 492,
  [SMALL_STATE(28)] = 507,
  [SMALL_STATE(29)] = 522,
  [SMALL_STATE(30)] = 537,
  [SMALL_STATE(31)] = 552,
  [SMALL_STATE(32)] = 567,
  [SMALL_STATE(33)] = 577,
  [SMALL_STATE(34)] = 591,
  [SMALL_STATE(35)] = 601,
  [SMALL_STATE(36)] = 611,
  [SMALL_STATE(37)] = 621,
  [SMALL_STATE(38)] = 630,
  [SMALL_STATE(39)] = 639,
  [SMALL_STATE(40)] = 650,
  [SMALL_STATE(41)] = 661,
  [SMALL_STATE(42)] = 672,
  [SMALL_STATE(43)] = 681,
  [SMALL_STATE(44)] = 692,
  [SMALL_STATE(45)] = 701,
  [SMALL_STATE(46)] = 709,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 5, 0, 8),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 5, 0, 8),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 7),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 3, 0, 7),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 2, 0, 3),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 2, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 3, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 3, 0, 4),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 5),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 3, 0, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 3, 0, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 5),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 5),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include, 4, 0, 4),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include, 4, 0, 4),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 4, 0, 7),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 4, 0, 7),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 6, 0, 8),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 6, 0, 8),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 6, 0, 9),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 6, 0, 9),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name, 1, 0, 2),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name, 1, 0, 1),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1, 0, 6),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__name, 2, 0, 1),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_type_name, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 2, 0, 6),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_comment = 0,
  ts_external_token_string = 1,
  ts_external_token__parameter_value = 2,
  ts_external_token__simple_value = 3,
  ts_external_token__include_path = 4,
  ts_external_token__array_value = 5,
  ts_external_token__array_open = 6,
  ts_external_token__unexpected_line_break = 7,
  ts_external_token__quoted_type = 8,
  ts_external_token__quoted_include_keyword = 9,
  ts_external_token__text_after_nul = 10,
  ts_external_token__separator = 11,
  ts_external_token__error_sentinel = 12,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_string] = sym_string,
  [ts_external_token__parameter_value] = sym__parameter_value,
  [ts_external_token__simple_value] = sym__simple_value,
  [ts_external_token__include_path] = sym__include_path,
  [ts_external_token__array_value] = sym__array_value,
  [ts_external_token__array_open] = sym__array_open,
  [ts_external_token__unexpected_line_break] = sym__unexpected_line_break,
  [ts_external_token__quoted_type] = sym__quoted_type,
  [ts_external_token__quoted_include_keyword] = sym__quoted_include_keyword,
  [ts_external_token__text_after_nul] = sym__text_after_nul,
  [ts_external_token__separator] = sym__separator,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[14][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__parameter_value] = true,
    [ts_external_token__simple_value] = true,
    [ts_external_token__include_path] = true,
    [ts_external_token__array_value] = true,
    [ts_external_token__array_open] = true,
    [ts_external_token__unexpected_line_break] = true,
    [ts_external_token__quoted_type] = true,
    [ts_external_token__quoted_include_keyword] = true,
    [ts_external_token__text_after_nul] = true,
    [ts_external_token__separator] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__quoted_include_keyword] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [3] = {
    [ts_external_token_comment] = true,
    [ts_external_token__quoted_type] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [4] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__quoted_include_keyword] = true,
    [ts_external_token__text_after_nul] = true,
    [ts_external_token__separator] = true,
  },
  [5] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__include_path] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [6] = {
    [ts_external_token_comment] = true,
    [ts_external_token__text_after_nul] = true,
    [ts_external_token__separator] = true,
  },
  [7] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__array_value] = true,
    [ts_external_token__text_after_nul] = true,
    [ts_external_token__separator] = true,
  },
  [8] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__include_path] = true,
    [ts_external_token__text_after_nul] = true,
    [ts_external_token__separator] = true,
  },
  [9] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__array_value] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [10] = {
    [ts_external_token_comment] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [11] = {
    [ts_external_token_comment] = true,
    [ts_external_token__array_open] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [12] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__parameter_value] = true,
    [ts_external_token__text_after_nul] = true,
  },
  [13] = {
    [ts_external_token_comment] = true,
    [ts_external_token_string] = true,
    [ts_external_token__simple_value] = true,
    [ts_external_token__text_after_nul] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_blk_external_scanner_create(void);
void tree_sitter_blk_external_scanner_destroy(void *);
bool tree_sitter_blk_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_blk_external_scanner_serialize(void *, char *);
void tree_sitter_blk_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_blk(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_blk_external_scanner_create,
      tree_sitter_blk_external_scanner_destroy,
      tree_sitter_blk_external_scanner_scan,
      tree_sitter_blk_external_scanner_serialize,
      tree_sitter_blk_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "blk",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
